### ISSUE TITLE
Release notes not being generated due to usage of main as branch name

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.7zip#19]
Out of the box, GitReleaseManager assumes that the target branch for generating release notes is the `master` branch, however, it doesn't have to be, this can be configured through parameters in the recipe.cake file.

**Comment by gep13** [comment]
@nils-a ah, looks like you have already got to this:

https://github.com/cake-contrib/Cake.7zip/commit/9e2914be75e5fa7e67633da06112438b145eccb4

Glad that you were able to find it.

**Comment by gep13** [comment]
@nils-a what are your thoughts around the name of that parameter, `masterBranchName`, should this be called something else?

**Comment by devlead** [comment]
`primaryBranch` or perhaps `releaseNotesBranch`

**Comment by nils-a** [comment]
interesting question. technically it's the "target_commitish". Though - thats "only" the branch the relase-notes get parsed from, right?

**Comment by gep13** [comment]
The targetCommitish, can be a tag, a branch name, or a commit hash, so it can be a few things, but given the primary use case, the main branch name, has always worked.  I think I will mull over the naming options, and perhaps change the parameter name in Cake.Recipe.

**Comment by gep13** [comment]
@devlead I like those suggestions.
